using GrandTheftMultiplayer.Shared;

namespace Enums
{
  public enum VehicleHashMotorcycles
  {
    Akuma = VehicleHash.Akuma,
    Avarus = VehicleHash.Avarus,
    Bagger = VehicleHash.Bagger,
    Bati2 = VehicleHash.Bati2,
    Bati = VehicleHash.Bati,
    Bf400 = VehicleHash.Bf400,
    Blazer4 = VehicleHash.Blazer4,
    CarbonRs = VehicleHash.CarbonRS,
    Chimera = VehicleHash.Chimera,
    Cliffhanger = VehicleHash.Cliffhanger,
    Daemon2 = VehicleHash.Daemon2,
    Daemon = VehicleHash.Daemon,
    Defiler = VehicleHash.Defiler,
    Double = VehicleHash.Double,
    Enduro = VehicleHash.Enduro,
    Esskey = VehicleHash.Esskey,
    Faggio2 = VehicleHash.Faggio2,
    Faggio3 = VehicleHash.Faggio3,
    Faggio = VehicleHash.Faggio,
    Fcr2 = VehicleHash.Fcr2,
    Fcr = VehicleHash.Fcr,
    Gargoyle = VehicleHash.Gargoyle,
    Hakuchou2 = VehicleHash.Hakuchou2,
    Hakuchou = VehicleHash.Hakuchou,
    Hexer = VehicleHash.Hexer,
    Innovation = VehicleHash.Innovation,
    Lectro = VehicleHash.Lectro,
    Manchez = VehicleHash.Manchez,
    Nemesis = VehicleHash.Nemesis,
    Nightblade = VehicleHash.Nightblade,
    Pcj = VehicleHash.PCJ,
    Ratbike = VehicleHash.Ratbike,
    Ruffian = VehicleHash.Ruffian,
    Sanchez2 = VehicleHash.Sanchez2,
    Sanchez = VehicleHash.Sanchez,
    Sanctus = VehicleHash.Sanctus,
    Shotaro = VehicleHash.Shotaro,
    Sovereign = VehicleHash.Sovereign,
    Thrust = VehicleHash.Thrust,
    Vader = VehicleHash.Vader,
    Vindicator = VehicleHash.Vindicator,
    Vortex = VehicleHash.Vortex,
    Wolfsbane = VehicleHash.Wolfsbane,
    Zombiea = VehicleHash.Zombiea,
    Zombieb = VehicleHash.Zombieb
  }
}
