using GrandTheftMultiplayer.Shared;

namespace Enums
{
  public enum VehicleHashSport
  {
    Alpha = VehicleHash.Alpha,
    Banshee = VehicleHash.Banshee,
    Banshee2 = VehicleHash.Banshee2,
    BestiaGts = VehicleHash.Bestiagts,
    Buffalo = VehicleHash.Buffalo,
    Buffalo2 = VehicleHash.Buffalo2,
    Buffalo3 = VehicleHash.Buffalo3,
    Carbonizzare = VehicleHash.Carbonizzare,
    Comet2 = VehicleHash.Comet2,
    Comet3 = VehicleHash.Comet3,
    Coquette = VehicleHash.Coquette,
    Elegy = VehicleHash.Elegy,
    Elegy2 = VehicleHash.Elegy2,
    Feltzer2 = VehicleHash.Feltzer2,
    Feltzer3 = VehicleHash.Feltzer3,
    Furoregt = VehicleHash.Furoregt,
    Fusilade = VehicleHash.Fusilade,
    Futo = VehicleHash.Futo,
    Infernus2 = VehicleHash.Infernus2,
    Jester = VehicleHash.Jester,
    Jester2 = VehicleHash.Jester2,
    Khamelion = VehicleHash.Khamelion,
    Kuruma = VehicleHash.Kuruma,
    Kuruma2 = VehicleHash.Kuruma2,
    Lynx = VehicleHash.Lynx,
    Massacro = VehicleHash.Massacro,
    Massacro2 = VehicleHash.Massacro2,
    Ninef = VehicleHash.Ninef,
    Ninef2 = VehicleHash.Ninef2,
    Omnis = VehicleHash.Omnis,
    Penumbra = VehicleHash.Penumbra,
    RapidGt = VehicleHash.RapidGT,
    RapidGt2 = VehicleHash.RapidGT2,
    Raptor = VehicleHash.Raptor,
    Ruston = VehicleHash.Ruston,
    Schafter2 = VehicleHash.Schafter2,
    Schafter3 = VehicleHash.Schafter3,
    Schafter4 = VehicleHash.Schafter4,
    Schafter5 = VehicleHash.Schafter5,
    Schafter6 = VehicleHash.Schafter6,
    Schwarzer = VehicleHash.Schwarzer,
    Seven70 = VehicleHash.Seven70,
    Specter = VehicleHash.Specter,
    Specter2 = VehicleHash.Specter2,
    Sultan = VehicleHash.Sultan,
    Surano = VehicleHash.Surano,
    Tampa2 = VehicleHash.Tampa2,
    Tropos = VehicleHash.Tropos,
    Verlierer2 = VehicleHash.Verlierer2,
  }
}
